#!/bin/sh
#############################################################################
# Backup utilities for aastra-xml-scripts
#
# Copyright 2008-2010 Aastra Telecom Ltd
#
# Usage
# 	./backup
# 
#############################################################################

# Get current date
date=`date '+%Y%2m%2d'`

# Go to the right directory
echo -n Creating backup........................................
tar cfz /tmp/aastra_backup_$date.tgz /var/cache/aastra/*.context /var/cache/aastra/*.cfg /var/cache/aastra/pictures /var/www/html/aastra/asterisk/*.prf /var/www/html/aastra/config/*.conf /var/cache/aastra/pictures >/dev/null 2>/dev/null
echo Done

# Echo for the user
echo Backup file is /tmp/aastra_backup_$date.tgz